name: test-push
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  test:
    name: Run tests on node ${{ matrix.node_version }} and {{ matrix.os}}
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          node_version: [12.x]
          os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Cache Node.js modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install chromedriver
      uses: actions/setup-chromedriver@v1.0.1
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run ci-test
    - name: Verify
      run: npm run cy-verify
    - name: E2E
      run: npm run ci-e2e
